/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lqm_ndkjnistudy_Hello */

#ifndef _Included_com_lqm_ndkjnistudy_Hello
#define _Included_com_lqm_ndkjnistudy_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lqm_ndkjnistudy_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lqm_ndkjnistudy_Hello_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
